/** Synthetic lifecycle fixture: no model or provider is called. */
import { writeFileSync, mkdirSync } from 'node:fs';
import { createHarnessProfile, captureRequestContext } from '../../src/context-capture.js';
import { reconcileContextBundles } from '../../src/context.js';
import { createContextReport } from '../../src/context-report.js';
import { valueEvidence } from '../../src/core.js';
import type { ContextBlockInput, ContextOrigin } from '../../src/context-types.js';
import type { EvidenceBundle } from '../../src/types.js';
const dataset_id='synthetic-context-lifecycle';
const artifact={id:'synthetic-transcript',harness:'fixture',format:'synthetic',coverage:'complete' as const,description:'Synthetic demonstration; token weights and monetary amounts are illustrative.'};
const profile=createHarnessProfile({harness:'fixture',harness_version:'1',name:'Illustrative coding harness',model:'fixture-model',provider:'fixture',policies:{compaction:{value:'Explicit producer-supplied summary',evidence:'declared',source_refs:[]}},instruction_sources:[{origin:'repository_instruction',label:'AGENTS.md (illustrative)',delivery:'always',evidence:'declared',source_refs:[]},{origin:'skill',label:'TDD instructions (illustrative)',delivery:'conditional',evidence:'declared',source_refs:[]}]});
const block=(source_id:string,origin:ContextOrigin,label:string,content:string,tokens:string,placement:ContextBlockInput['placement']='instruction',representation:ContextBlockInput['representation']='original'):ContextBlockInput=>({source_id,origin,origin_evidence:'declared',label,representation,media:'text',role:origin==='assistant_output'?'assistant':origin==='tool_result'?'tool':'user',placement,content,tokens:{value:tokens,unit:'tokens',evidence:'estimated',method:'Illustrative synthetic token weight; not a provider token count',source_refs:[{source_id:artifact.id,record:source_id}]}});
const instructions=block('repo-instructions','repository_instruction','AGENTS.md','Use public interface tests and preserve exact integer accounting.','60');
const skill=block('skill','skill','TDD skill','Write a failing test before the smallest production change.','80');
const file=block('file','repository_file','allocation.ts','Allocate signed integer amounts and preserve the unknown portion.','140','current_turn','excerpt');
const prompt=block('prompt','user_prompt','Task request','Add context allocation.','20','current_turn');
const output=block('assistant','assistant_output','Earlier response','I will expose unavailable context and conserve every nanounit.','40','history');
const tool=block('test-result','tool_result','Test output','All allocation checks passed.','50','tool_result');
const summary=block('summary','conversation_history','Compaction summary','Allocation implemented. Exact costs are preserved; missing context stays unallocated.','70','history','summary');
const followup=block('followup','user_prompt','Follow-up request','Explain the remaining coverage.','15','current_turn');
const inputs=[[instructions,skill,file,prompt],[instructions,skill,file,prompt,output,tool],[instructions,summary,followup]];
const calls=[{id:'request-1',input:'400',amount:'0.0025'},{id:'request-2',input:'650',amount:'0.0045'},{id:'request-3',input:'220',amount:'0.0018'}];
const evidence:EvidenceBundle={schema_version:'0.1.0',dataset_id,sources:[artifact],relationships:[{from:'request-1',to:'request-2',kind:'context_from'},{from:'request-2',to:'request-3',kind:'context_from'}],issues:[{code:'SYNTHETIC_FIXTURE',severity:'info',message:'Illustrative token weights, outcomes and cost values; no provider call was made.'}],observations:calls.map((call,i)=>({id:call.id,kind:'model',operation:['Inspect allocation','Implement and test','Explain coverage'][i]!,status:'ok',accounting_scope:'direct',timestamp:`2026-09-06T10:0${i}:00Z`,agent_id:'fixture-coder',model:'fixture-model',model_identity:'setting',source_refs:[{source_id:artifact.id,record:call.id}],usage:{input_tokens:call.input,output_tokens:'50',cache_read_input_tokens:null,cache_write_input_tokens:null,reasoning_output_tokens:null},recorded_cost:{amount:call.amount,currency:'USD',basis:'model_price_estimate'}}))};
const context=reconcileContextBundles(calls.map((call,i)=>captureRequestContext({dataset_id,request_id:`context-${call.id}`,observation_id:call.id,captured_at:`2026-09-06T10:0${i}:00Z`,profile,boundary:'client_request',coverage:'partial',coverage_evidence:'declared',artifact,record:call.id,blocks:inputs[i]!})),evidence);
context.transformations.push({id:'compact-1',kind:'compact',from_revision_ids:context.revisions.filter(r=>['file','prompt','assistant','test-result'].includes(r.source_id)).map(r=>r.id),to_revision_ids:context.revisions.filter(r=>r.source_id==='summary').map(r=>r.id),evidence:'declared',method:'Synthetic producer-declared compaction lineage; retained instructions are not ancestors of the summary.',observation_id:null,source_refs:[{source_id:artifact.id,record:'compact-1'}]});
const report=createContextReport(evidence,valueEvidence(evidence,{mode:'recorded'}),context,{allocation_request_ids:context.requests.map(r=>r.id)});
mkdirSync('examples/context',{recursive:true});
writeFileSync('examples/context/lifecycle-report.json',JSON.stringify(report,null,2)+'\n');
console.log({dataset_id,requests:report.summary.requests,sources:report.summary.context_sources,total_nanos:report.valuation.total_nanos});
