// Throwaway, version-specific evidence extractor. Explicit files only; never scans sessions.
// node extract.cjs OUTPUT CUTOFF alias=FILE ...
const fs=require('fs'),crypto=require('crypto');const [output,cutoff,...sources]=process.argv.slice(2);
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
let calls=[],activities=[],compactions=[],threads=[],turnIds=new Map(),seen=new Set(),duplicates=0;const turn=x=>{if(!turnIds.has(x))turnIds.set(x,'turn '+String(turnIds.size+1).padStart(2,'0'));return turnIds.get(x)};
const keys=['input_tokens','cached_input_tokens','cache_write_input_tokens','output_tokens','reasoning_output_tokens','total_tokens'];
for(const src of sources){const i=src.indexOf('='),alias=src.slice(0,i),file=src.slice(i+1);const all=fs.readFileSync(file,'utf8').split('\n').filter(Boolean);const rows=all.map((s,i)=>({s,line:i+1,o:JSON.parse(s)})).filter(r=>r.o.timestamp<=cutoff);const meta=rows.find(r=>r.o.type==='session_meta').o.payload;let context={},last=null,seq=0,counts={},events=0,localCalls=[];for(const {o,line} of rows){const p=o.payload;counts[o.type+':'+(p.type||'')]=(counts[o.type+':'+(p.type||'')]||0)+1;if(o.type==='turn_context'){context=p;turn(p.root_turn_id||p.turn_id)}if(o.type==='token_usage_record'){const id=p.thread_id+':'+p.response_id;if(seen.has(id)){duplicates++;continue}seen.add(id);last=p;const c={id:alias+' call '+String(++seq).padStart(3,'0'),responseHash:hash(id).slice(0,16),agent:alias,turn:turn(p.root_turn_id||p.turn_id),localTurn:turn(p.turn_id),model:context.model||'unknown',effort:context.effort||'unknown',time:o.timestamp,line,ordinal:o.ordinal,...p.usage};calls.push(c);localCalls.push(c)}if(o.type==='event_msg'&&p.type==='item_completed'){const it=p.item;if(['CommandExecution','Extension','FileChange','SubAgentActivity','McpToolCall','ContextCompaction'].includes(it.type)){activities.push({agent:alias,turn:turn(p.turn_id),time:o.timestamp,line,kind:it.type,tool:it.type==='McpToolCall'?it.server+'/'+it.tool:it.type==='Extension'?it.kind:it.type==='SubAgentActivity'?it.kind:it.type,status:it.status??null,start:p.started_at_ms??null,end:p.completed_at_ms??null});events++}}if(o.type==='compacted')compactions.push({agent:alias,time:o.timestamp,line,window:p.window_number,responseIdPresent:!!p.compaction_response_id,usageSnapshotDuplicatesEarlier:seen.has(p.latest_token_usage_record?.thread_id+':'+p.latest_token_usage_record?.response_id)});}
const sum=Object.fromEntries(keys.map(k=>[k,localCalls.reduce((s,c)=>s+(c[k]??0),0)]));threads.push({agent:alias,parent:meta.parent_thread_id?'coordinator':null,version:meta.cli_version,sourceHash:hash(rows.map(r=>r.s).join('\n')),rows:rows.length,counts,callCount:localCalls.length,activityCount:events,sum,reported:last?.thread_token_usage,reconciled:!!last&&keys.every(k=>sum[k]===last.thread_token_usage[k]),lastUsageTime:localCalls.at(-1)?.time});}
const total=Object.fromEntries(keys.map(k=>[k,calls.reduce((s,c)=>s+(c[k]??0),0)]));const checks={everyThreadReconciles:threads.every(t=>t.reconciled),duplicateUsageRecords:duplicates,inputPlusOutputEqualsTotal:calls.every(c=>c.input_tokens+c.output_tokens===c.total_tokens),cacheWithinInput:calls.every(c=>c.cached_input_tokens+c.cache_write_input_tokens<=c.input_tokens),reasoningWithinOutput:calls.every(c=>c.reasoning_output_tokens<=c.output_tokens),uniqueResponseHashes:new Set(calls.map(c=>c.responseHash)).size===calls.length};
const data={description:'Sanitized current-conversation evidence. No prompts, results, raw identifiers or reasoning content. This is a frozen partial run, not a bill.',cutoff,accounting:'Only token_usage_record.usage is additive. Thread totals validate, not add. Cache and reasoning are subsets. No external charge data.',workMapping:'All four agents belong to one conversation. Ticket/epic labels in demo are analyst-assigned example grouping, not observed work IDs.',total,checks,threads,calls,activities,compactions};fs.writeFileSync(output,JSON.stringify(data,null,2)+'\n');console.log(JSON.stringify({cutoff,calls:calls.length,activities:activities.length,total,checks,threads:threads.map(t=>({agent:t.agent,calls:t.callCount,sum:t.sum.total_tokens,reconciled:t.reconciled})),compactions},null,2));
